export default {
    light:{
        navColor:'grey lighten-3',
        background: 'grey lighten-2',
        titleText1: 'light-blue-text text-lighten-3',
        titleText2: 'cyan-text text-darken-4',
        text1: 'black-text',
        text2: 'grey-text text-darken-2',
        button: 'indigo lighten-3',
        buttonText: 'black-text',
        current: 'light'
    },
    dark: {
        navColor:'black',
        background: 'grey darken-2',
        titleText1: "white-text",
        titleText2: 'teal-text',
        text1: 'white-text',
        text2: 'grey-text text-darken-1',
        button: 'grey darken-4',
        buttonText: 'purple-text text-accent-3',
        current: 'dark'
    },
    gotham: {
        navColor: 'grey darken-4',
        background: 'grey darken-3',
        titleText1: "cyan-text text-accent-4",
        titleText2: 'orange-text text-accent-2',
        text1: 'green-text text-accent-3',
        text2: 'grey-text text-darken-3',
        button: 'cyan accent-4',
        buttonText: 'white-text ',
        current: 'gotham'
    },
    panda: {
        navColor: 'grey darken-4',
        background: 'grey darken-2',
        titleText1: 'light-blue-text lighten-4',
        titleText2: 'pink-text lighten-3',
        text1: 'white-text',
        text2: 'cyan-text lighten-2',
        button: 'orange lighten-2',
        buttonText: 'pink-text',
        current: 'panda',
    },
    monokai: {
        navColor: 'grey darken-3',
        background: 'grey darken-1',
        titleText1: 'pink-text accent-3',
        titleText2: 'light-green-text accent-3',
        text1: 'white-text',
        text2: 'orange-text darken-1',
        button: 'light-blue lighten-2',
        buttonText: 'yellow-text lighten-2',
        current: 'monokai',
    },
    soldark: {
        navColor: 'light-blue darken-3',
        background: 'light-blue darken-4',
        titleText1: 'light-green-text darken-2',
        titleText2: 'light-green-text darken-2',
        text1: 'white-text',
        text2: 'cyan-text lighten-1',
        button: 'deep-purple lighten-1',
        buttonText: 'white-text',
        current: 'soldark',
    },
    quietlight: {
        navColor: 'grey lighten-5',
        background: 'grey lighten-4',
        titleText1: 'red-text darken-4',
        titleText2: 'blue-text lighten-1',
        text1: 'black-text',
        text2: 'purple-text',
        button: 'deep-green lighten-1',
        buttonText: 'white-text lighten-3',
        current: 'quietlight',
    },
    sublime: {
        navColor: 'grey darken-3',
        background: 'blue-grey darken-4',
        titleText1: 'blue-text lighten-3',
        titleText2: 'red-text darken-1',
        text1: 'grey-text',
        text2: 'purple-text lighten-3',
        button: 'light-green darken-2',
        buttonText: 'white-text lighten-3',
        current: 'sublime',
    }
}